version: "3.5"
services:
  transaction-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-app
    tty: true
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    networks:
        - transaction-network
    depends_on:
        - db

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    - "8000:8000"
    - "443:443"
    volumes:
      - ./:/var/www:delegated
      - ./nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
        - transaction-network

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/:delegated
      - ./mysql/my.cnf:/etc/mysql/my.cnf:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transactiondb
    networks:
        - transaction-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8002:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - transaction-network

volumes:
  dbdata:
    driver: local

networks:
  transaction-network:
    name: transaction-network
#    driver: bridge
