<?php


namespace App\Modules\Transaction\Service;


use App\Exceptions\TransactionException;
use App\Mail\NotifyReceiptMail;
use App\Modules\Transaction\Repository\TransactionRepositoryInterface;
use App\Modules\Transaction\TransactionEntity;
use App\Modules\Transaction\Validation\ProcessValidationsInterface;
use App\Modules\TransactionAuthorizer\Service\TransactionAuthorizerServiceInterface;
use App\Modules\User\Service\UserService;
use App\Modules\User\Service\UserServiceInterface;
use App\Modules\User\UserEntity;
use App\Modules\Wallet\Service\WalletServiceInterface;
use App\Send\SendNotification;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Mail;

class TransactionService implements TransactionServiceInterface
{

    /**
     * @var TransactionRepositoryInterface
     */
    private $transactionRepository;

    /**
     * @var UserServiceInterface
     */
    private $userService;

    /**
     * @var TransactionAuthorizerServiceInterface
     */
    private $authorizerService;

    /**
     * @var ProcessValidationsInterface
     */
    private $processValidations;

    /**
     * @var WalletServiceInterface
     */
    private $walletService;

    public function __construct(
        TransactionRepositoryInterface $transactionRepository,
        UserServiceInterface $userInterface,
        TransactionAuthorizerServiceInterface $authorizerService,
        ProcessValidationsInterface $processValidations,
        WalletServiceInterface $walletService
    )
    {
        $this->transactionRepository = $transactionRepository;
        $this->userService = $userInterface;
        $this->authorizerService = $authorizerService;
        $this->processValidations = $processValidations;
        $this->walletService = $walletService;
    }

    /**
     * @inheritDoc
     */
    public function getTransactions(): array
    {
        return $this->transactionRepository->getTransactions();
    }

    /**
     * @inheritDoc
     */
    public function makeTransaction(int $payerId, int $payeeId, float $value): TransactionEntity
    {
        try {
            // Find the payer/payee users and their wallets
            $userPayer = $this->userService->getUserAndWallet($payerId);
            $userPayee = $this->userService->getUserAndWallet($payeeId);

            // Process all the validations required for payer user
            $transactionPermitted = $this->processValidations->validateTransaction($userPayer, $userPayee, $value, $this->authorizerService);
            if (!$transactionPermitted) {
                throw new TransactionException('A transferência não foi autorizada para este pagador. Cheque as informações e tente novamente.', Response::HTTP_UNAUTHORIZED);
            }

            return $this->userToUserTransaction($userPayer, $userPayee, $value);

        } catch (TransactionException $transactionException) {
            throw $transactionException;
        } catch (\Exception | \TypeError $exception) {
            throw new TransactionException('Ocorreu um erro ao realizar a transferência.', Response::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    /**
     * Save the modifications generated by the new transaction
     * (withdraw from user payer; deposit into payee's wallet;
     * insert a new transaction record).
     * @param UserEntity $payer
     * @param UserEntity $payee
     * @param float $value
     * @return TransactionEntity
     * @throws TransactionException
     */
    private function userToUserTransaction(UserEntity $payer, UserEntity $payee, float $value): TransactionEntity
    {
        $this->walletService->withdraw($payer, $value);
        $this->walletService->deposit($payee, $value);

        return $this->transactionRepository->newTransaction($payer, $payee, $value);
    }

    /**
     * @inheritDoc
     */
    public function notifyTransactionPayee(TransactionEntity $transactionEntity): bool
    {
        $payee = $this->userService->getUserAndWallet($transactionEntity->getPayeeId());

        if (!$payee) {
            throw new \Exception('Usuário não encontrado!', Response::HTTP_NOT_FOUND);
        }

        $payer = $this->userService->getUserAndWallet($transactionEntity->getPayerId());

        try {
            // Mock the notification send
//            return SendNotification::notificate($payee);

            // Send an e-mail to payee user
            Mail::to($payee->getEmail())->send(new NotifyReceiptMail($payee, $payer, $transactionEntity));
            return true;
        } catch (\Exception $exception) {
            throw $exception;
        }
    }
}
